"""create initial tables

Revision ID: 37c3fc51eb7a
Revises: 
Create Date: 2025-05-27 13:09:29.143293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c3fc51eb7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lokasi',
    sa.Column('id_lokasi', sa.Integer(), nullable=False),
    sa.Column('nama_lokasi', sa.String(length=100), nullable=False),
    sa.Column('kode_lokasi', sa.String(length=50), nullable=False),
    sa.Column('alamat_lokasi', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_lokasi', name=op.f('pk_lokasi')),
    sa.UniqueConstraint('kode_lokasi', name=op.f('uq_lokasi_kode_lokasi'))
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PENANGGUNG_JAWAB', 'VIEWER', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id_user', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('barang',
    sa.Column('id_barang', sa.Integer(), nullable=False),
    sa.Column('nama_barang', sa.String(length=200), nullable=False),
    sa.Column('kode_barang', sa.String(length=100), nullable=False),
    sa.Column('kondisi', sa.Enum('BAIK', 'RUSAK_RINGAN', 'RUSAK_BERAT', name='kondisibarang'), nullable=False),
    sa.Column('id_lokasi', sa.Integer(), nullable=False),
    sa.Column('penanggung_jawab', sa.String(length=50), nullable=False),
    sa.Column('tanggal_masuk', sa.DateTime(), nullable=False),
    sa.Column('tanggal_pembaruan', sa.DateTime(), nullable=True),
    sa.Column('gambar_aset', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_lokasi'], ['lokasi.id_lokasi'], name=op.f('fk_barang_id_lokasi_lokasi')),
    sa.PrimaryKeyConstraint('id_barang', name=op.f('pk_barang')),
    sa.UniqueConstraint('kode_barang', name=op.f('uq_barang_kode_barang'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barang')
    op.drop_table('users')
    op.drop_table('lokasi')
    # ### end Alembic commands ###
