"""init

Revision ID: 370d391587ee
Revises: 
Create Date: 2025-05-29 23:01:03.181410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370d391587ee'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lokasi',
    sa.Column('nama_lokasi', sa.String(length=100), nullable=False),
    sa.Column('kode_lokasi', sa.String(length=50), nullable=False),
    sa.Column('alamat_lokasi', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lokasi')),
    sa.UniqueConstraint('kode_lokasi', name=op.f('uq_lokasi_kode_lokasi'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PENANGGUNG_JAWAB', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('barang',
    sa.Column('nama_barang', sa.String(length=200), nullable=False),
    sa.Column('kode_barang', sa.String(length=100), nullable=False),
    sa.Column('kondisi', sa.Enum('BAIK', 'RUSAK_RINGAN', 'RUSAK_BERAT', name='kondisibarang'), nullable=False),
    sa.Column('id_lokasi', sa.Integer(), nullable=False),
    sa.Column('penanggung_jawab', sa.String(length=50), nullable=False),
    sa.Column('tanggal_masuk', sa.DateTime(), nullable=False),
    sa.Column('tanggal_pembaruan', sa.DateTime(), nullable=True),
    sa.Column('gambar_aset', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_lokasi'], ['lokasi.id'], name=op.f('fk_barang_id_lokasi_lokasi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barang')),
    sa.UniqueConstraint('kode_barang', name=op.f('uq_barang_kode_barang'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barang')
    op.drop_table('users')
    op.drop_table('lokasi')
    # ### end Alembic commands ###
